-- ============================================================
--  FinSight – Personal Finance & Investment Intelligence Platform
--  File       : database.sql
--  Description: MySQL Database Schema and Seed Data
--  Import via : phpMyAdmin or MySQL Workbench
-- ============================================================

-- Step 1: Create Database Schema if it does not already exist
-- utf8mb4 encoding ensures support for international text and emojis
CREATE DATABASE IF NOT EXISTS finsight
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

-- Step 2: Select and switch to the newly created finsight database
USE finsight;

-- ============================================================
--  Table: users
--  Stores registered user profile data and encrypted passwords
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  -- id: Unique auto-incrementing integer identifier for each registered user
  id          INT AUTO_INCREMENT PRIMARY KEY,
  
  -- name: User's full display name
  name        VARCHAR(100)  NOT NULL,
  
  -- email: User's login email address (must be unique across all records)
  email       VARCHAR(100)  NOT NULL UNIQUE,
  
  -- password: Store bcrypt encrypted hash string (255 characters reserved for salt+hash)
  password    VARCHAR(255)  NOT NULL,
  
  -- created_at: Automatic registration timestamp generated by MySQL server
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
--  Sample Seed Data: Demo Account
--  User     : Demo User
--  Email    : demo@finsight.com
--  Password : Test@1234 (Pre-encrypted using bcrypt salt)
-- ============================================================
INSERT INTO users (name, email, password) VALUES
  (
    'Demo User',
    'demo@finsight.com',
    '$2b$12$KIXxLpf4q1cTaV3sYlQS9.GZtN5f.kFQzPqFdD8Xr1BkW2jH7eIBm'
  );

-- Verification Query: Output existing user records
SELECT id, name, email, created_at FROM users;
